[net]
git-fetch-with-cli = true
[registries]
ustc = { index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/" }
[source]
crates-io = { replace-with = "ustc" }
ustc      = { registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/" }
