apiVersion: apps/v1
kind: Deployment
metadata:
  name: flector
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: flector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flector
    spec:
      serviceAccountName: flector
      containers:
        - name: flector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
