apiVersion: v1
kind: ServiceAccount
metadata:
  name: flector
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flector
rules:
  - apiGroups: ["flector.io"]
    resources: ["flects", "flects/status"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flector
subjects:
  - kind: ServiceAccount
    name: flector
    namespace: {{ .Release.Namespace }}
